apiVersion: apps/v1
kind: Deployment
metadata:
  name: sarna-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sarna-app
  template:
    metadata:
      labels:
        app: sarna-app
    spec:
      containers:
      - name: sarna-app
        image: sarna-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: sarna-app-service
spec:
  type: NodePort
  selector:
    app: sarna-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001
